### ISSUE TITLE
The specified device interface or feature level is not supported on this system.

### ISSUE THREAD

**Issue by anpin** [vvvv/VL.ScreenRecorder#1]
Hello, thanks for your effort. When I'm trying to run sample it shows following error after I try to hit record button

Error message: "The specified device interface or feature level is not supported on this system."

**Comment by joreg** [comment]
hey anpin,

unfortunately this is a [known issue with the underlying library](https://github.com/sskodje/ScreenRecorderLib/issues/63) used. so for now the only way this works is by explicitly starting vvvv with the integrated graphics card.

**Comment by anpin** [comment]
@joreg thanks for quick response. I'm wondering if there is another way to workaround it since my project is already CPU heavy and a bit choppy in times. I'm thinking running it through Gstreamer could work (or getting a proper PC :)). What about using the enum flag as suggested in the original thread, could this be done somehow within VL? Also I'm wondering if the bug might cause another issue I had here, which is Skia off-screen accelerated renderer  is either shows black screen, or draws something completely different from what I can see in the non accelerated renderer and then crashes.

**Comment by anpin** [comment]
Actually I just looked back in the project with a fresh pair of eyes and it is not particularly heavy load, but still quite a bit choppy

**Comment by joreg** [comment]
re the original issue we'll have to wait for an update of the underlying library.
re the other issues you mentioned i suggest you open a forum thread on discourse.vvvv.org as they don't sound related to this library.
